name: Deploy Astro Blog to VPS

on:
  push:
    branches:
      - astro

jobs:
  deps-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ github.workspace }}

      - name: Build Astro app
        run: pnpm run build
        working-directory: ${{ github.workspace }}

      - name: Clean remote directory
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} '
            rm -rf /var/www/blog/*
          '

      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --force
          path: dist/
          remote_path: /var/www/blog
          remote_host: ${{ secrets.VPS_IP }}
          remote_user: ${{ secrets.VPS_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
